name: Mini CI

on: push

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Run tests
        run: ./mvnw test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build project
        run: ./mvnw package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: mini-ci-jar
          path: target/*.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download JAR artifact
        uses: actions/download-artifact@v8
        with:
          name: mini-ci-jar
          path: target

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t mini-ci .

      - name: Save image
        run: docker save mini-ci:latest -o mini-ci.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: mini-ci-image-tar
          path: mini-ci.tar
